In [24]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

EIN                                      NAME APPLICATION_TYPE  \
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10   
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0       Independent          C1000    ProductDev   Association       1   
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [25]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
app_df_cleaned = application_df.drop(columns=['EIN', 'NAME'])
app_df_cleaned.head(2)

APPLICATION_TYPE  AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  \
0              T10  Independent          C1000    ProductDev   Association   
1               T3  Independent          C2000  Preservation  Co-operative   

   STATUS INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0       1          0                      N     5000              1  
1       1     1-9999                      N   108590              1

In [26]:
# Determine the number of unique values in each column.
app_df_cleaned.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [27]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_count = app_df_cleaned['APPLICATION_TYPE'].value_counts()
app_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [28]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_count[app_count < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [29]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_count = app_df_cleaned['CLASSIFICATION'].value_counts()
class_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [30]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_count[class_count > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [31]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count[class_count < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [32]:
# Convert categorical data to numeric with `pd.get_dummies`
app_df_cleaned = pd.get_dummies(app_df_cleaned)
app_df_cleaned.head()

STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  \
0       1     5000              1                  True                 False   
1       1   108590              1                 False                 False   
2       1     5000              0                 False                 False   
3       1     6692              1                 False                 False   
4       1   142590              1                 False                 False   

   APPLICATION_TYPE_T13  APPLICATION_TYPE_T14  APPLICATION_TYPE_T15  \
0                 False                 False                 False   
1                 False                 False                 False   
2                 False                 False                 False   
3                 False                 False                 False   
4                 False                 False                 False   

   APPLICATION_TYPE_T17  APPLICATION_TYPE_T19  ...  INCOME_AMT_1-9999  \
0                 False                 False  ...              False   
1                 False                 False  ...               True   
2                 False                 False  ...              False   
3                 False                 False  ...              False   
4                 False                 False  ...              False   

   INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  INCOME_AMT_10M-50M  \
0                   False                     False               False   
1                   False                     False               False   
2                   False                     False               False   
3                    True                     False               False   
4                   False                      True               False   

   INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  INCOME_AMT_50M+  \
0             False                   False            False   
1             False                   False            False   
2             False                   False            False   
3             False                   False            False   
4             False                   False            False   

   INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y  
0              False                      True                     False  
1              False                      True                     False  
2              False                      True                     False  
3              False                      True                     False  
4              False                      True                     False  

[5 rows x 117 columns]

In [33]:
# Split our preprocessed data into our features and target arrays
X = app_df_cleaned.drop(columns=['IS_SUCCESSFUL']).values
Y = app_df_cleaned['IS_SUCCESSFUL'].values

In [34]:
X[0]

array([1, 5000, True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, True, False, False, False, False, True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, True, True,
       False, False, False, True, False, False, False, False, False,
       False, False, False, True, False], dtype=object)

In [36]:
Y

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

In [39]:
X_train[0]

array([1, 5000, False, False, False, False, False, False, False, False,
       False, False, True, False, False, False, False, False, False, True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, True, False, True,
       False, False, False, True, False, False, False, False, False,
       False, False, False, True, False], dtype=object)

In [40]:
X_test[0]

array([1, 5000, False, False, False, False, False, False, False, False,
       False, False, True, False, False, False, False, False, False, True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, True, False,
       False, False, False, True, True, False, False, False, False, False,
       False, False, False, True, False], dtype=object)

In [41]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
print(X_train_scaled[0])

[ 0.01394306 -0.03180216 -0.12551965 -0.02789425 -0.04413044 -0.00623504
 -0.00623504 -0.00623504 -0.177999   -0.022486   -0.00881785 -0.00623504
  0.51847585 -0.21828898 -0.1895294  -0.18930918 -0.14670825 -0.15053376
 -0.06493162  1.08525817 -0.04323714 -1.07823435 -0.02925687 -0.01247081
 -0.01870803 -0.01079982 -1.01015889 -0.40221139 -0.03180805 -0.00881785
 -0.01649829 -0.00623504 -0.01763775 -0.01649829 -0.03180805  0.
 -0.00881785 -0.00623504 -0.02160343 -0.00881785 -0.01079982 -0.01079982
  0.         -0.06120378 -0.01763775 -0.03795283  0.         -0.04186173
  0.         -0.03416998 -0.022486   -0.00623504 -0.00623504 -0.01079982
 -0.09643059 -0.01394306 -0.00623504 -0.00623504 -0.02068331 -0.00623504
 -0.00623504 -0.46362006  4.17613977 -0.00623504 -0.00623504 -0.00623504
 -0.02789425  0.         -0.01079982 -0.00623504 -0.00623504 -0.00623504
 -0.00623504 -0.05585372 -0.00881785 -0.05260901 -0.2445854  -0.00881785
 -0.00623504 -0.07423929 -0.01394306 -0.00623504 -0.0062350

In [57]:
X_train = X_train.astype('float32')

In [58]:
import tensorflow as tf

# Define the model architecture
def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(128, activation='relu', input_shape=(input_dim,)),
        tf.keras.layers.Dropout(0.5),  # Dropout for regularization
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')  # Output layer
    ])
    return model


In [59]:
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

# Define the model architecture
def create_model(input_dim):
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(128, activation='relu', input_shape=(input_dim,)),
        tf.keras.layers.Dropout(0.5),  # Dropout for regularization
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dense(1, activation='sigmoid')  # Output layer
    ])
    return model

# Create the model
model = create_model(input_dim=X_train.shape[1])

# Define a learning rate schedule
initial_lr = 0.001
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=initial_lr,
    decay_steps=10000,
    decay_rate=0.9
)

# Compile the model
model.compile(
    optimizer=Adam(learning_rate=lr_schedule),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Define the early stopping callback
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)


In [60]:
# Assuming x_train and y_train are your training data and labels
history = model.fit(
    X_train, Y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping]
)


Epoch 1/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.5064 - loss: 74792.7109 - val_accuracy: 0.4799 - val_loss: 36605.9648
Epoch 2/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4940 - loss: 24626.1289 - val_accuracy: 0.4799 - val_loss: 43999.0195
Epoch 3/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5096 - loss: 24987.2129 - val_accuracy: 0.5201 - val_loss: 71621.7812
Epoch 4/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4976 - loss: 14671.9629 - val_accuracy: 0.5201 - val_loss: 9337.0332
Epoch 5/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4959 - loss: 22711.2754 - val_accuracy: 0.4799 - val_loss: 7789.3535
Epoch 6/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5153 - loss: 22046.7305 - val_accuracy: 0.4799 - val_loss: 15821.6582
Epoch 7/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5023 - loss: 11284.3398 - val_accuracy: 0.5293 - val_loss: 228.3714
Epoch 8/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step 

In [54]:
# Save the model
model.save('AlphabetSoupCharity_Optimization.h5')

# Load the model
loaded_model = tf.keras.models.load_model('AlphabetSoupCharity_Optimization.h5')
loaded_model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                      │ (None, 128)                 │          14,976 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 25,346 (99.01 KB)

 Trainable params: 25,345 (99.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1 (8.00 B)